// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.Ursula.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc0.Ursula.Robot;

import constants.ShooterConstants;

/**
 *
 */
public class RollBallOut extends Command {

	ShooterConstants constant = new ShooterConstants();
	
    public RollBallOut() {
    	//Need the shooter subsystem to exist, so we check that it exists
    	requires(Robot.shooter);
    	//Set a timer for how long the function runs for
    	setTimeout(constant.lowGoalShotTime());
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.shooter.lowGoalShoot();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	//When the timer is timed out (after the # of seconds defined above,) this will return true
    	//and execute() will stop being called
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.shooter.intakeOff();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	//Calls the end() method from above
    	end();
    }
}
